/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'secondary-dim': '#eb8d00',
        'primary-container': '#00ffff',
        'tertiary-fixed': '#c6f4f3',
        'tertiary-fixed-dim': '#b8e5e4',
        'primary': '#c1fffe',
        'on-secondary-fixed': '#4f2c00',
        'secondary-fixed-dim': '#ffb466',
        'secondary': '#fe9800',
        'on-primary-container': '#005d5d',
        'primary-dim': '#00e6e6',
        'on-surface-variant': '#aaabac',
        'error-dim': '#d7383b',
        'inverse-on-surface': '#545556',
        'on-secondary': '#4a2900',
        'surface-container-low': '#111415',
        'surface-tint': '#c1fffe',
        'surface-variant': '#232628',
        'on-tertiary-fixed': '#1f4b4b',
        'surface-container-lowest': '#000000',
        'error': '#ff716c',
        'on-background': '#f6f6f7',
        'surface': '#0c0e0f',
        'inverse-surface': '#f9f9fa',
        'tertiary-dim': '#abd7d6',
        'on-error-container': '#ffa8a3',
        'outline': '#747577',
        'background': '#0c0e0f',
        'surface-container': '#181a1b',
        'primary-fixed-dim': '#00e6e6',
        'on-primary-fixed': '#004343',
        'surface-dim': '#0c0e0f',
        'surface-container-high': '#1d2021',
        'primary-fixed': '#00f5f5',
        'secondary-fixed': '#ffc790',
        'on-secondary-container': '#fff6f1',
        'tertiary': '#e2fffe',
        'outline-variant': '#464849',
        'surface-bright': '#2a2c2e',
        'on-tertiary-container': '#335e5d',
        'surface-container-highest': '#232628',
        'error-container': '#9f0519',
        'inverse-primary': '#006a6a',
        'on-primary': '#006767',
        'secondary-container': '#8a5100',
        'on-tertiary-fixed-variant': '#3d6868',
        'on-surface': '#f6f6f7',
        'on-primary-fixed-variant': '#006262',
        'tertiary-container': '#c6f4f3',
        'on-error': '#490006',
        'on-tertiary': '#3c6666',
        'on-secondary-fixed-variant': '#774500',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
      fontFamily: {
        'headline': ['Space Grotesk'],
        'body': ['Inter'],
        'label': ['Space Grotesk'],
        'mono': ['JetBrains Mono'],
      },
    },
  },
  plugins: [],
}
